#!/usr/bin/env python3

import sys
import argparse
import os
from mattermostdriver import Driver

env = {}

class MattermostError(RuntimeError):
    pass

def fetch_env_var(name, msg):
	if name not in env:
		try:
			env[name] = os.environ[name]
		except KeyError:
			raise MattermostError('Missing environment variable \'{}\': {}'.format(name, msg))
	return env[name]

def fetch_all_env():
	env_local = {'MATTERMOST_ACCESS_TOKEN': 'Add you personal access token for Mattermost.'}
	for var, msg in env_local.items():
		fetch_env_var(var, msg)

def upload(message, filename, team, channel, url):
	token    = env['MATTERMOST_ACCESS_TOKEN']

	foo = Driver({
	    'url': url,
	    'token': token,
	    'scheme': 'http',
	    'port': 80,
	})

	foo.login()

	# To upload a file you will need to pass a `files` dictionary
	channel_id = foo.channels.get_channel_by_name_and_team_name(team, channel)['id']
	file_id = foo.files.upload_file(
    	channel_id=channel_id,
    	files={'files': (filename, open(filename, 'rb'))}
	)['file_infos'][0]['id']


	# track the file id and pass it in `create_post` options, to attach the file
	foo.posts.create_post(options={
	'channel_id': channel_id,
	'message': message,
	'file_ids': [file_id]})

if __name__ == '__main__':
	parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter, description='')
	parser.add_argument('-m', '--message', nargs='+',
	                    help='Message')
	parser.add_argument('-f', '--files', default='',
	                    help='Files to link in the message.')
	parser.add_argument('-t', '--team', help='The name of the team')
	parser.add_argument('-c', '--channel', help='The name of the channel')
	parser.add_argument('-u', '--url', help='The url of Mattermost')
	args = parser.parse_args()
	arg_str = ' '.join(args.message)
	try:
		fetch_all_env()
		upload(arg_str, args.files, args.team, args.channel, args.url)
	except MattermostError as err:
		print(err)
		sys.exit(1)
